# https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL: '/'
languageCode: 'en-us'
title: '海山道神社'
Copyright: 'Miyamadojinja'

# https://gohugo.io/variables/site/#the-siteparams-variable
params:
  logoImage: 'img/logo.svg'
  officeAddress: '三重県四日市市海山道町1丁目62番地'
  officeMapUrl: 'https://www.google.com/maps/place/Miyamado+Shrine/@34.9430372,136.6211072,18z'
  officeEmail: 'miyamado@m7.cty-net.ne.jp'
  officePhone: '059-345-5419'
  twitterUrl: https://twitter.com/search?q=%E6%B5%B7%E5%B1%B1%E9%81%93%E7%A5%9E%E7%A4%BE
  facebookUrl: https://www.facebook.com/%E6%B5%B7%E5%B1%B1%E9%81%93%E7%A5%9E%E7%A4%BE-137077743078473
  instagramUrl: https://www.instagram.com/miyamado_shrine
  description: |
    Amet adipisicing labore aliqua cupidatat nisi ut velit. Laboris est esse
    labore in veniam aliquip elit aliquip. Aute eiusmod magna occaecat esse aliqua.

# https://gohugo.io/content-management/menus
menu:
  main:
    - name: 'Docs 1'
      url: '#'
      weight: 1
    - name: 'Docs 2 '
      url: '#'
      weight: 1
    - name: 'Docs 3'
      url: '#'
      weight: 1

# https://gohugo.io/content-management/taxonomies/
taxonomies:
  tag: tags
